server:
  port: 8087

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/springboot
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

application:
   endpoints:
      ml-app:
         timeout: 10
         base-url: "https://reqres.in/api"
         get-gender: "/users"
         
spring:
   profiles:
      active: #spring.profiles.active#
   http:
      multipart:
         max-file-size: 5MB
         max-request-size: 5MB